### ISSUE TITLE
Escape character

### ISSUE THREAD

**Issue by bekinin** [zenedge/logs_cli#1]
The string which caused error was "% 20HDMI \ x99" 
below see:

"Request": {"request_line": "GET /bin/st/servlets/xreference.json?searchKey=ESD%20protection%20and%20signal%20conditioning%20for%20HDMI\x99%202.0%20and%20%20HDMI\x99%%% 201.4% 20source & saveQuery = false & rand = 1499983355110 HTTP / 1.1 "

**Comment by Nikamura** [comment]
Newest version fixed this issue.
